In [1]:
import numpy as np

In [5]:
np.random.random()

0.4799473905236935

In [7]:
np.random.seed(12)
np.random.random()

0.15416284237967237

In [ ]:
np.random.uniform(3, 10) # lying bw 3 and 10


9.431229056699195

In [ ]:
np.random.uniform(1,100,10).reshape(2,5) #float

array([[55.65172569, 49.05236395, 77.04528125, 16.91095856, 76.69148458],
       [ 3.06017   , 14.38580766, 12.51102872, 31.67986086, 67.47381188]])

In [ ]:
np.random.randint(1,10,15).reshape(3,5) #integer

array([[5, 2, 6, 6, 4],
       [5, 6, 6, 1, 7],
       [7, 4, 3, 5, 4]], dtype=int32)

In [21]:
a=np.random.randint(1,10,15).reshape(3,5)
a

array([[4, 3, 7, 5, 6],
       [1, 1, 6, 5, 1],
       [4, 8, 7, 9, 7]], dtype=int32)

In [22]:
np.max(a)

np.int32(9)

In [23]:
# argmax -> returns the max no index
np.argmax(a)

np.int64(13)

In [24]:
# argmin -> returns the min no index
np.argmin(a)

np.int64(5)

In [ ]:
a[a%2==1]=-1 # replacing odd no with -1, but its changing the original array
a

array([[ 4, -1, -1, -1,  6],
       [-1, -1,  6, -1, -1],
       [ 4,  8, -1, -1, -1]], dtype=int32)

In [28]:
# using where when we dont need to change the original array
a=np.random.randint(1,20,6)
a

array([10,  3,  5, 17, 13,  5], dtype=int32)

In [29]:
# creating another arry for modifications and original array remains the same
np.where(a%2==1, -1, a)

array([10, -1, -1, -1, -1, -1], dtype=int32)

In [ ]:
a # not changed!

array([10,  3,  5, 17, 13,  5], dtype=int32)

In [ ]:
a=np.random.randint(1,50,10)
a

array([36,  8, 31, 37, 47, 11, 13, 20,  9, 27], dtype=int32)

In [33]:
a=np.sort(a)
a

array([ 8,  9, 11, 13, 20, 27, 31, 36, 37, 47], dtype=int32)

In [34]:
# percentile
np.percentile(a, 25)

np.float64(11.5)

In [36]:
np.percentile(a,50)

np.float64(23.5)