# Indexing, Slicing

single element extraction = indexing
multi element extraction = slicing

slicing generic formula = arr[ row_start : row_stop , col_start : col_stop ]

In [2]:
import numpy as np

In [3]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr1[0]

np.int64(1)

In [6]:
arr1[2:4]

array([3, 4])

In [7]:
arr1[-1]

np.int64(5)

In [8]:
arr1[:-1]

array([1, 2, 3, 4])

In [9]:
arr12[2]

array([ 8,  9, 10, 11])

In [ ]:
arr12[:,3] # extracting 4th row 

array([ 3,  7, 11, 15, 19, 23])

In [14]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [ ]:
arr12[:,2:4] # row 2 se 4 tk

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [27]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [28]:
arr12[3:5, 2:4]

array([[14, 15],
       [18, 19]])

## Common Patterns
## What you want to extract   

1. A single specific element arr[row, col]  arr12[3, 2] -> 14
2. An entire single row arr[row_index, :]arr12[2, :] -> [8, 9, 10, 11]
3. An entire single column  arr[:, col_index]arr12[:, 1] -> [1, 5, 9, 13, 17, 21]
4. First 2 rows, all columns arr[-2:, -2:] -> [[18, 19], [22, 23]]
5. Last 2 rows, last 2 columns  arr[-2:, -2:] -> [[18, 19], [22, 23]]
6. Every alternate row/col arr[::2, ::2]	Takes step size of 2 across both dimensions

In [29]:
arr12 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [31]:
# item by ite printing

for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
