# 6 differet kind of array
1. np.array()/1-d and 2d
2. using np.zeroes()
3. using np.arange()
4. using np.linespace()
5. using copy()
6. using identity()

## creating numpy/n-d arrays

In [12]:
import numpy as np

In [13]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [14]:
type(arr1)

numpy.ndarray

In [15]:
arr2=np.array([[1,2,3],[5,6,7]])
arr2

array([[1, 2, 3],
       [5, 6, 7]])

### method 2

In [16]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

### method 3

In [17]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### method 4

In [19]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### method 5

In [21]:
arr6=np.arange(1,10,2)
arr6

array([1, 3, 5, 7, 9])

### method 6

In [23]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

### method 7

In [24]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])