# 6 differet kind of array
1. np.array()/1-d and 2d
2. using np.zeroes()
3. using np.arange()
4. using np.linespace()
5. using copy()
6. using identity()

## creating numpy/n-d arrays

In [12]:
import numpy as np

In [13]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [14]:
type(arr1)

numpy.ndarray

In [15]:
arr2=np.array([[1,2,3],[5,6,7]])
arr2

array([[1, 2, 3],
       [5, 6, 7]])

### method 2

In [16]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

### method 3

In [17]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### method 4

In [19]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### method 5

In [21]:
arr6=np.arange(1,10,2)
arr6

array([1, 3, 5, 7, 9])

### method 6

In [23]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

### method 7

In [24]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# properties and attributes

In [26]:
arr2.shape

(2, 3)

In [32]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## shape (rows,columns,block)

In [31]:
arr9.shape


(2, 2, 2)

## ndim (dimention?)

In [33]:
arr9.ndim

3

In [34]:
arr2.ndim

2

## size (no of items)

In [35]:
arr1.size

5

In [36]:
arr9.size

8

## item size (item X its size)

In [37]:
arr9.itemsize

8

In [38]:
arr8.itemsize

8

## dtype data type

In [39]:
arr8.dtype

dtype('float64')

In [40]:
arr9.dtype

dtype('int64')

## type conversion

In [42]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

## numpy array vs lists
1. faster
2. convenient
3. less memory

### less memory proving

In [44]:
lista = range(100) # list
arr11=np.arange(100) # np array

In [45]:
import sys

In [46]:
# using get size of
print(sys.getsizeof(87)*len(lista)) # getting size of 1 item


2800


In [ ]:
print(arr11.itemsize*arr11.size) ## np stores an element is less amount of memory

800


### how fast??

In [48]:
import time

In [54]:
x=range(10000000)
y=range(100000, 200000)

start_time = time.time()
c=[x+y for x,y in zip(x,y)] ## zip and add1,1 item and store in c
print(time.time()-start_time)


0.006460666656494141


In [56]:
a=np.arange(10000000)
b=np.arange(10000000, 20000000)
Start_time=time.time()
c= a+b # auto adds single,single element and forms new
print(time.time()-Start_time)

0.025951623916625977
