# reshaping the numpy arrays 
1. ravel()
2. reshape()
3. Transpose()
4. stacking()
5. splitting

In [4]:
import numpy as np

## ravel() higher dimension array ko lower ma lata

In [6]:
arr4 = np.arange(6,12).reshape(3,2)
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [7]:
arr4.ndim

2

In [8]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [10]:
arr4.shape

(3, 2)

## transpose()

In [ ]:
arr4.transpose() row ko col, col ko row

array([[ 6,  8, 10],
       [ 7,  9, 11]])

## stacking() a trick to combine 2 arrays

In [12]:
arr5=np.arange(12,18).reshape(2,3)
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [13]:
arr3 = np.arange(6).reshape(2,3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.hstack((arr3, arr5)) # hstack horizontally stack krta ha 

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [17]:
np.vstack((arr3,arr5)) # vstack vertically stack krta ha

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

## spliting

In [19]:
np.hsplit(arr3, 3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [20]:
np.vsplit(arr3, 2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]